version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./frontend:/app/frontend
      - ./contract:/app/contract
    environment:
      - NODE_ENV=development
      - PORT=8000
      - NEXT_PUBLIC_API_URL
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app/backend
      - ./contract:/app/contract
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - ./backend/.env

volumes:
  node_modules_frontend:
  node_modules_backend:
